from coppeliasim_zmqremoteapi_client import RemoteAPIClient

# ESTADOS DEL ROBOT
AVANZAR_RECTO     = 1
GIRAR_IZQUIERDA   = 2
GIRAR_DERECHA     = 3
GIRAR_180_GRADOS  = 4

# PARÁMETROS DE MOVIMIENTO
VELOCIDAD_AVANCE = 2.0
VELOCIDAD_GIRO   = 2.2

# UMBRALES DE DISTANCIA (m)
DISTANCIA_PARED    = 0.30
DISTANCIA_PELIGRO  = 0.15
DISTANCIA_OBJETIVO = 0.45

# TIEMPOS DE GIRO (s)
TIEMPO_GIRO_90_GRADOS = 1.0
TIEMPO_SOBREGIRO      = 0.4
